id: I87809961
ocr_import_info:
  bdrc_scan_id: W1KG16613
  source: bdrc
  ocr_info:
    timestamp: '2023-02-01T00:00:00Z'
  batch_id: batch-0001
  software_id: norbuketaka
  expected_default_language: bo
  op_import_options: null
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-09-12 14:04:30.085601
last_modified: 2023-02-01 00:00:00+00:00
parser: https://github.com/OpenPecha/Norbu-Keta-eText-import/blob/main/norbu_ketaka_parser.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG16613
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW8LS76628
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཇོ་བོའི་ཆོས་འབྱུང་བརྒྱ་རྩ།
  languages:
  - bo
  author: སློབ་དཔོན་དཔའ་བོ།
bases:
  I1KG16661:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16661
      total_pages: 570
      volume_number: 1
      volume_pages_bdrc_intro: 2
    base_file: I1KG16661.txt
    order: 1
copyright:
  status: Public domain
  notice: The proofread texts are donated by the Norbu Ketaka project led by Queenie
    Luo (Harvard University), Zhiying Li (Sichuan University) and Leonard van der
    Kuijp (Harvard University). Correspondence should be directed to  queenieluo@g.harvard.edu
license: CC0
